from cmssw/slc6-vanilla
MAINTAINER Marco Rovere marco.rovere@cern.ch

ENV INSTALL_DIR=/data/srv
ENV HTTPG_VERSION=HG1704h
ENV ARCH=slc6_amd64_gcc493
ENV COMP=comp.rovere
ENV DQMGUI_VERSION=@9.0.1
EXPOSE 8060

RUN yum install -y git \
                   HEP_OSlibs_SL6 \
                   e2fsprogs \
                   hostname

# We need to run under a user different from root, since our software will not install using the root account
RUN useradd dqmgui && install -o dqmgui -d /data
USER dqmgui

RUN mkdir -p ${INSTALL_DIR}/ && cd ${INSTALL_DIR}
WORKDIR ${INSTALL_DIR}
RUN git clone git://github.com/dmwm/deployment.git cfg && cd cfg && git reset --hard ${HTTPG_VERSION}
RUN cfg/Deploy -r "comp=${COMP}" -A ${ARCH} -R comp@${HTTPG_VERSION} -t ${HTTPG_VERSION} -s "prep sw post" $PWD dqmgui${DQMGUI_VERSION}/bare

# Now set up sphinx to allow developing and building

RUN . $PWD/current/*/*/external/apt/*/etc/profile.d/init.sh && \
    $PWD/current/sw.rovere/common/cmspkg  -a slc6_amd64_gcc493 install -y external+py2-sphinx+1.1.3

USER root

CMD source ${INSTALL_DIR}/current/sw.rovere/${ARCH}/cms/dqmgui/*/128/etc/profile.d/init.sh && ${INSTALL_DIR}/current/config/dqmgui/manage restart 'I did read documentation' && while true; do sleep 100; done
